version: '3.8'

services:
  backend:
    build: .
    container_name: gpu-sentinel-backend
    restart: always
    ports:
      - "5183:5183"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - gpu-net

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gpu-sentinel-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - gpu-net

networks:
  gpu-net:
    name: gpu-net
    external: true  # Use existing network where Ollama containers run
